__all__ = (
    "DEFAULT_NAME",
    "DEFAULT_URL",
    "DEFAULT_DIRECTORY",
    "DEFAULT_OUTPUT",
    "DEFAULT_TITLE_LEVEL",
    "DEFAULT_SECTION_LEVEL",
    "DEFAULT_BULLET",
    "DEFAULT_WRAP",
    "DEFAULT_WRAP_SIZE",
    "DEFAULT_START_STRING",
    "DEFAULT_TITLE_FORMAT",
    "DEFAULT_ISSUE_FORMAT",
)

EMPTY = str()

DEFAULT_NAME = "changelogging"

DEFAULT_URL = EMPTY
DEFAULT_DIRECTORY = "changes"
DEFAULT_OUTPUT = "CHANGELOG.md"
DEFAULT_TITLE_LEVEL = 2
DEFAULT_SECTION_LEVEL = 3
DEFAULT_BULLET = "-"
DEFAULT_WRAP = False
DEFAULT_WRAP_SIZE = 80
DEFAULT_START_STRING = "<!-- changelogging: start -->"
DEFAULT_TITLE_FORMAT = "{name} {version} ({date})"
DEFAULT_ISSUE_FORMAT = "#{issue}"
DEFAULT_FRAGMENT_FORMAT = "{content} ({issue})"
