name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build

    strategy:
      matrix:
        config:
          - os: ubuntu
            output: target/release/changelogging
          - os: macos
            output: target/release/changelogging
          - os: windows
            output: target/release/changelogging.exe

    runs-on: ${{ matrix.config.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: changelogging-${{ matrix.config.os }}
          path: ${{ matrix.config.output }}
