name: release

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu
            target: x86_64-unknown-linux-gnu
            output: changelogging

          - os: macos
            target: x86_64-apple-darwin
            output: changelogging

          - os: macos
            target: aarch64-apple-darwin
            output: changelogging

          - os: windows
            target: x86_64-pc-windows-msvc
            output: changelogging.exe

          - os: windows
            target: aarch64-pc-windows-msvc
            output: changelogging.exe

    runs-on: ${{ matrix.config.os }}-latest

    env:
      file: ${{ matrix.config.output }}
      copy: target/release/${{ matrix.config.output }}
      name: changelogging-${{ github.ref_name }}-${{ matrix.config.target }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.target }}

      - name: Build
        run: cargo build --release

      - name: Archive (ubuntu)
        if: matrix.config.os == 'ubuntu'
        run: |
          cp ${{ env.copy }} ${{ env.file }}
          tar -cvzf ${{ env.name }}.tar.gz ${{ env.file }}

      - name: Archive (macos)
        if: matrix.config.os == 'macos'
        run: |
          cp ${{ env.copy }} ${{ env.file }}
          zip ${{ env.name }}.zip ${{ env.file }}

      - name: Archive (windows)
        if: matrix.config.os == 'windows'
        run: |
          copy ${{ env.copy }} ${{ env.file }}
          7z a ${{ env.name }}.zip ${{ env.file }}

      - name: Upload
        uses: actions/upload-artifact@v4

        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4

        with:
          path: archives
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2

        with:
          files: archives/*
          fail_on_unmatched_files: true
