name: release

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu
            target: x86_64-unknown-linux-gnu
            extension: ""

          - os: macos
            target: x86_64-apple-darwin
            extension: ""

          - os: macos
            target: aarch64-apple-darwin
            extension: ""

          - os: windows
            target: x86_64-pc-windows-msvc
            extension: ".exe"

          - os: windows
            target: aarch64-pc-windows-msvc
            extension: ".exe"

    runs-on: ${{ matrix.config.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.config.target }}

      - name: Build
        run: cargo build --release

      - name: Upload
        uses: actions/upload-artifact@v4

        with:
          name: changelogging-${{ matrix.config.target }}
          path: target/release/changelogging${{ matrix.config.extension }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4

        with:
          path: outputs
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2

        with:
          files: outputs
