name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release

    strategy:
      matrix:
        config:
          - os: ubuntu
            output: target/release/changelogging
          - os: macos
            output: target/release/changelogging
          - os: windows
            output: target/release/changelogging.exe

    runs-on: ${{ matrix.config.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Build release changelog
        run: cargo run build --preview > CHANGELOG_${{ github.ref_name }}.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.config.output }}
          body_path: CHANGELOG_${{ github.ref_name }}.md
